# Generated by Django 5.0 on 2023-12-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='transaccion_id',
        ),
    ]
